- name: Instalando pacotes do MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb
    - python3-devel
    - mysql-devel
    - mariadb-connector-c.x86_64
    - mariadb-connector-odbc.x86_64
  when: ansible_facts['distribution'] == "CentOS"

- name: Instalando o MYSQL-python
  pip:
    name: mariadb
  when: ansible_facts['distribution'] == "CentOS"

- name: Enable service Mysql, and not touch the state
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == "CentOS"